-- GLOBAL NEWS24 AI NEWSROOM PHASE 8-2
-- Version: v3.12.1
-- Purpose: duplicate submission protection + newsroom audit log.

alter table public.gn24_reporter_submissions
  add column if not exists client_submission_key text;

create unique index if not exists gn24_reporter_submissions_reporter_client_key_uq
  on public.gn24_reporter_submissions(reporter_id, client_submission_key)
  where client_submission_key is not null and client_submission_key <> '';

create table if not exists public.gn24_submission_audit (
  id bigint generated by default as identity primary key,
  submission_id uuid not null,
  reporter_id text not null default '',
  action text not null,
  from_status text,
  to_status text,
  actor_user_id uuid,
  actor_role text not null default '',
  changed_fields text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists gn24_submission_audit_submission_idx
  on public.gn24_submission_audit(submission_id, created_at desc);
create index if not exists gn24_submission_audit_created_idx
  on public.gn24_submission_audit(created_at desc);

alter table public.gn24_submission_audit enable row level security;
revoke all on table public.gn24_submission_audit from anon;
revoke insert, update, delete on table public.gn24_submission_audit from authenticated;
grant select on table public.gn24_submission_audit to authenticated;

drop policy if exists "gn24 audit admin editor read" on public.gn24_submission_audit;
create policy "gn24 audit admin editor read"
on public.gn24_submission_audit
for select to authenticated
using (is_gn24_admin() or gn24_my_access_level() = 'editor');

-- The production trigger function records only changed field names and workflow states,
-- not copies of reporter facts or verification contact data.
-- Execute privilege is revoked from API roles; it runs only through the table trigger.
