-- GLOBAL NEWS24 v3.24.0 — GN24 DAILY RECORD V1
-- Article source of truth: gn24_articles.date + is_published + region_code.
-- The editorial date column is already a date (KST business date), so no UTC cast is used.

create extension if not exists pgcrypto;

create table if not exists public.gn24_daily_records (
  id uuid primary key default gen_random_uuid(),
  record_date date not null unique,
  headline text not null default '', summary text not null default '',
  publisher_note text, hero_image_url text,
  news_count integer, domestic_news_count integer, global_news_count integer,
  active_country_count integer, active_region_count integer,
  milestone_count integer not null default 0, development_count integer not null default 0,
  verification_status text not null default 'SYSTEM AUTO VERIFIED'
    check (verification_status in ('SYSTEM AUTO VERIFIED','ADMIN VERIFIED','HISTORY CANDIDATE')),
  next_action text,
  status text not null default 'draft' check (status in ('draft','published','locked','archived')),
  published_at timestamptz, locked_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.gn24_daily_events (
  id uuid primary key default gen_random_uuid(),
  daily_record_id uuid not null references public.gn24_daily_records(id) on delete restrict,
  event_date date not null, occurred_at timestamptz, recorded_at timestamptz not null default now(),
  event_type text not null check (event_type in ('NEWS','EDITION','REGION','NETWORK','DEVELOPMENT','ORGANIZATION','PARTNERSHIP','AWARD','MILESTONE','SPECIAL')),
  title text not null, description text not null default '',
  problem text, action_taken text, result text,
  importance text not null default 'NORMAL' check (importance in ('NORMAL','IMPORTANT','HISTORIC')),
  verification_status text not null default 'ADMIN VERIFIED'
    check (verification_status in ('SYSTEM AUTO VERIFIED','ADMIN VERIFIED','HISTORY CANDIDATE')),
  history_level text not null default 'RECORD' check (history_level in ('RECORD','MILESTONE','HISTORY')),
  history_candidate boolean not null default false,
  evidence_grade text, evidence_type text check (evidence_type is null or evidence_type in ('DATABASE','ARTICLE','GIT','OFFICIAL DOCUMENT','ADMIN CONFIRMATION','EXTERNAL SOURCE')),
  evidence_reference text, source_url text, image_url text,
  is_public boolean not null default true, display_order integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint gn24_daily_history_candidate_guard check (history_level <> 'HISTORY' or history_candidate = true)
);

create table if not exists public.gn24_daily_snapshots (
  id uuid primary key default gen_random_uuid(), record_date date not null unique,
  daily_record_id uuid not null unique references public.gn24_daily_records(id) on delete restrict,
  total_articles integer, daily_articles integer,
  total_global_editions integer, active_global_editions integer,
  total_korea_regions integer, active_korea_regions integer,
  total_countries integer, network_members integer, reporters integer, branches integer,
  country_breakdown jsonb, region_breakdown jsonb, unknown_breakdown jsonb,
  snapshot_version text not null default '1.0', created_at timestamptz not null default now()
);

create table if not exists public.gn24_record_metrics (
  id bigint generated by default as identity primary key,
  metric_date date not null, metric_key text not null, metric_value numeric,
  previous_value numeric, change_value numeric, source_type text not null default 'DATABASE',
  created_at timestamptz not null default now(), unique(metric_date,metric_key)
);

create index if not exists gn24_articles_daily_record_idx on public.gn24_articles(date,region_code) where is_published=true;
create index if not exists gn24_daily_events_record_idx on public.gn24_daily_events(daily_record_id,display_order,created_at);

create or replace function public.gn24_daily_record_guard() returns trigger language plpgsql set search_path=public as $$
begin
  if old.status='locked' and new is distinct from old then raise exception 'DAILY_RECORD_LOCKED'; end if;
  new.updated_at:=now(); return new;
end $$;
drop trigger if exists gn24_daily_record_guard_trg on public.gn24_daily_records;
create trigger gn24_daily_record_guard_trg before update on public.gn24_daily_records for each row execute function public.gn24_daily_record_guard();

create or replace function public.gn24_daily_event_guard() returns trigger language plpgsql set search_path=public as $$
begin
  if exists(select 1 from public.gn24_daily_records where id=new.daily_record_id and status='locked') then raise exception 'DAILY_RECORD_LOCKED'; end if;
  new.updated_at:=now(); return new;
end $$;
drop trigger if exists gn24_daily_event_guard_trg on public.gn24_daily_events;
create trigger gn24_daily_event_guard_trg before insert or update on public.gn24_daily_events for each row execute function public.gn24_daily_event_guard();

alter table public.gn24_daily_records enable row level security;
alter table public.gn24_daily_events enable row level security;
alter table public.gn24_daily_snapshots enable row level security;
alter table public.gn24_record_metrics enable row level security;
revoke all on public.gn24_daily_records, public.gn24_daily_events, public.gn24_daily_snapshots, public.gn24_record_metrics from anon, authenticated;
grant select,insert,update on public.gn24_daily_records, public.gn24_daily_events, public.gn24_daily_snapshots, public.gn24_record_metrics to authenticated;
grant usage,select on sequence public.gn24_record_metrics_id_seq to authenticated;

drop policy if exists "daily records admin" on public.gn24_daily_records;
create policy "daily records admin" on public.gn24_daily_records for all to authenticated using (public.is_gn24_admin()) with check (public.is_gn24_admin());
drop policy if exists "daily events admin" on public.gn24_daily_events;
create policy "daily events admin" on public.gn24_daily_events for all to authenticated using (public.is_gn24_admin()) with check (public.is_gn24_admin());
drop policy if exists "daily snapshots admin" on public.gn24_daily_snapshots;
create policy "daily snapshots admin" on public.gn24_daily_snapshots for all to authenticated using (public.is_gn24_admin()) with check (public.is_gn24_admin());
drop policy if exists "daily metrics admin" on public.gn24_record_metrics;
create policy "daily metrics admin" on public.gn24_record_metrics for all to authenticated using (public.is_gn24_admin()) with check (public.is_gn24_admin());

create or replace function public.gn24_daily_compute(p_date date)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  domestic text[] := array['seoul','busan','daegu','incheon','gwangju','daejeon','ulsan','sejong','gyeonggi','gangwon','chungbuk','chungnam','jeonbuk','jeonnam','gyeongbuk','gyeongnam','jeju'];
  registered text[];
  countries text[];
  v jsonb;
begin
  if not public.is_gn24_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if exists(select 1 from public.gn24_daily_records where record_date=p_date and status='locked') then raise exception 'DAILY_RECORD_LOCKED'; end if;
  if p_date is null or p_date > (now() at time zone 'Asia/Seoul')::date then raise exception 'INVALID_RECORD_DATE'; end if;
  select array_agg(distinct lower(m[1])) into registered
  from pg_constraint c
  cross join lateral regexp_matches(pg_get_constraintdef(c.oid),E'''([^'']+)''(?:::text)?','g') m
  where c.conrelid='public.gn24_articles'::regclass
    and c.contype='c'
    and pg_get_constraintdef(c.oid) ilike '%region_code%';
  if registered is null or not(domestic <@ registered) then raise exception 'REGION_REGISTRY_UNAVAILABLE'; end if;
  select array_agg(code order by code) into countries
  from unnest(registered) code
  where not(code=any(domestic));
  with a as (
    select nullif(lower(btrim(region_code)),'') code from public.gn24_articles
    where is_published=true and workflow_status='published' and visibility_scope='public' and date=p_date
  ), total as (select count(*)::int n from public.gn24_articles where is_published=true and workflow_status='published' and visibility_scope='public'),
  grouped as (select code,count(*)::int n from a group by code)
  select jsonb_build_object(
    'record_date',p_date,'news_count',(select count(*) from a),
    'domestic_news_count',(select count(*) from a where code=any(domestic)),
    'global_news_count',(select count(*) from a where code=any(countries)),
    'active_region_count',(select count(*) from grouped where code=any(domestic)),
    'active_country_count',(select count(*) from grouped where code=any(countries)),
    'unknown_count',(select count(*) from a where code is null or not(code=any(domestic)) and not(code=any(countries))),
    'total_articles',(select n from total),
    'regions',coalesce((select jsonb_agg(jsonb_build_object('code',code,'count',n) order by n desc,code) from grouped where code=any(domestic)),'[]'::jsonb),
    'countries',coalesce((select jsonb_agg(jsonb_build_object('code',code,'count',n) order by n desc,code) from grouped where code=any(countries)),'[]'::jsonb),
    'unknown',coalesce((select jsonb_agg(jsonb_build_object('code',code,'count',n) order by n desc,code) from grouped where code is null or not(code=any(domestic)) and not(code=any(countries))),'[]'::jsonb),
    'total_global_editions',array_length(countries,1),'total_korea_regions',array_length(domestic,1)
  ) into v;
  return v;
end $$;
revoke all on function public.gn24_daily_compute(date) from public,anon;
grant execute on function public.gn24_daily_compute(date) to authenticated;

create or replace function public.gn24_daily_publish(p_date date)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v jsonb; r public.gn24_daily_records; prev numeric; val numeric; k text;
begin
  if not public.is_gn24_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtext('gn24_daily:'||p_date::text));
  if exists(select 1 from public.gn24_daily_records where record_date=p_date and status='locked') then raise exception 'DAILY_RECORD_LOCKED'; end if;
  if exists(select 1 from public.gn24_daily_records where record_date=p_date and status in ('published','archived')) then
    return (select jsonb_build_object('id',id,'status',status,'published_at',published_at,'already_published',true) from public.gn24_daily_records where record_date=p_date);
  end if;
  v:=public.gn24_daily_compute(p_date);
  insert into public.gn24_daily_records(record_date,news_count,domestic_news_count,global_news_count,active_country_count,active_region_count,status,published_at,updated_at)
  values(p_date,(v->>'news_count')::int,(v->>'domestic_news_count')::int,(v->>'global_news_count')::int,(v->>'active_country_count')::int,(v->>'active_region_count')::int,'published',now(),now())
  on conflict(record_date) do update set news_count=excluded.news_count,domestic_news_count=excluded.domestic_news_count,global_news_count=excluded.global_news_count,active_country_count=excluded.active_country_count,active_region_count=excluded.active_region_count,status=case when gn24_daily_records.status='locked' then 'locked' else 'published' end,published_at=coalesce(gn24_daily_records.published_at,now()),updated_at=now()
  returning * into r;
  update public.gn24_daily_records set
    milestone_count=(select count(*) from public.gn24_daily_events where daily_record_id=r.id and importance in ('IMPORTANT','HISTORIC')),
    development_count=(select count(*) from public.gn24_daily_events where daily_record_id=r.id and event_type='DEVELOPMENT')
  where id=r.id returning * into r;
  insert into public.gn24_daily_snapshots(record_date,daily_record_id,total_articles,daily_articles,total_global_editions,active_global_editions,total_korea_regions,active_korea_regions,total_countries,country_breakdown,region_breakdown,unknown_breakdown)
  values(p_date,r.id,(v->>'total_articles')::int,(v->>'news_count')::int,(v->>'total_global_editions')::int,(v->>'active_country_count')::int,(v->>'total_korea_regions')::int,(v->>'active_region_count')::int,(v->>'total_global_editions')::int,v->'countries',v->'regions',v->'unknown')
  on conflict(record_date) do nothing;
  foreach k in array array['news_count','domestic_news_count','global_news_count','active_country_count','active_region_count','total_articles'] loop
    val=(v->>k)::numeric; select metric_value into prev from public.gn24_record_metrics where metric_key=k and metric_date<p_date order by metric_date desc limit 1;
    insert into public.gn24_record_metrics(metric_date,metric_key,metric_value,previous_value,change_value)
    values(p_date,k,val,prev,case when prev is null then null else val-prev end)
    on conflict(metric_date,metric_key) do update set metric_value=excluded.metric_value,previous_value=excluded.previous_value,change_value=excluded.change_value;
  end loop;
  return v||jsonb_build_object('id',r.id,'status',r.status,'published_at',r.published_at);
end $$;
revoke all on function public.gn24_daily_publish(date) from public,anon;
grant execute on function public.gn24_daily_publish(date) to authenticated;

create or replace function public.gn24_get_daily_record(p_date date default null)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare r public.gn24_daily_records; d date; out jsonb;
begin
  if p_date is not null and p_date>(now() at time zone 'Asia/Seoul')::date then return null; end if;
  select * into r from public.gn24_daily_records where status in ('published','locked','archived') and (p_date is null or record_date=p_date) order by record_date desc limit 1;
  if r.id is null then return null; end if; d=r.record_date;
  select jsonb_build_object(
    'record',jsonb_build_object('record_date',r.record_date,'headline',r.headline,'summary',r.summary,'publisher_note',r.publisher_note,'hero_image_url',r.hero_image_url,'news_count',r.news_count,'domestic_news_count',r.domestic_news_count,'global_news_count',r.global_news_count,'active_country_count',r.active_country_count,'active_region_count',r.active_region_count,'milestone_count',r.milestone_count,'development_count',r.development_count,'verification_status',r.verification_status,'status',r.status,'published_at',r.published_at),
    'events',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'event_date',e.event_date,'occurred_at',e.occurred_at,'event_type',e.event_type,'title',e.title,'description',e.description,'problem',e.problem,'action_taken',e.action_taken,'result',e.result,'importance',e.importance,'verification_status',e.verification_status,'history_candidate',e.history_candidate,'source_url',e.source_url,'image_url',e.image_url) order by e.display_order,e.created_at) from public.gn24_daily_events e where e.daily_record_id=r.id and e.is_public=true),'[]'::jsonb),
    'snapshot',(select to_jsonb(s)-'id'-'daily_record_id' from public.gn24_daily_snapshots s where s.daily_record_id=r.id),
    'previous_date',(select max(record_date) from public.gn24_daily_records where record_date<d and status in ('published','locked','archived')),
    'next_date',(select min(record_date) from public.gn24_daily_records where record_date>d and record_date<=(now() at time zone 'Asia/Seoul')::date and status in ('published','locked','archived'))
  ) into out; return out;
end $$;
revoke all on function public.gn24_get_daily_record(date) from public;
grant execute on function public.gn24_get_daily_record(date) to anon,authenticated;

insert into storage.buckets(id,name,public) values('daily-record-images','daily-record-images',true) on conflict(id) do update set public=true;
drop policy if exists "daily record image public read" on storage.objects;
create policy "daily record image public read" on storage.objects for select using(bucket_id='daily-record-images');
drop policy if exists "daily record image admin insert" on storage.objects;
create policy "daily record image admin insert" on storage.objects for insert to authenticated with check(bucket_id='daily-record-images' and public.is_gn24_admin());
