-- GLOBAL NEWS24 v3.21.1 — GN24 TODAY PHASE 1 FOUNDATION
-- Applied to GLOBAL-NEWS24 Supabase: 2026-09-25
-- NEWS != TODAY != AD
-- Foundation only: no main-page exposure, no comments, no points/ranks.

create table if not exists public.gn24_today_posts (
  id uuid primary key default gen_random_uuid(),
  author_user_id uuid not null default auth.uid(),
  author_display_name text not null default '',
  region_code text not null,
  category text not null default 'daily',
  title text not null default '',
  body text not null,
  image_url text,
  status text not null default 'pending' check (status in ('draft','pending','published','held','rejected','hidden')),
  approved_by uuid,
  approved_at timestamptz,
  hq_hidden boolean not null default false,
  featured boolean not null default false,
  news_candidate boolean not null default false,
  commercial_flag boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  hidden_at timestamptz,
  constraint gn24_today_region_nonempty check (length(btrim(region_code)) > 0),
  constraint gn24_today_body_nonempty check (length(btrim(body)) > 0)
);
create index if not exists gn24_today_posts_region_status_idx on public.gn24_today_posts(region_code,status,created_at desc);
create index if not exists gn24_today_posts_author_idx on public.gn24_today_posts(author_user_id,created_at desc);

create table if not exists public.gn24_today_audit (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.gn24_today_posts(id) on delete restrict,
  actor_user_id uuid,
  action text not null,
  old_status text,
  new_status text,
  region_code text not null,
  created_at timestamptz not null default now()
);
create index if not exists gn24_today_audit_post_idx on public.gn24_today_audit(post_id,created_at desc);

alter table public.gn24_today_posts enable row level security;
alter table public.gn24_today_audit enable row level security;
grant select on public.gn24_today_posts to anon, authenticated;
grant insert, update on public.gn24_today_posts to authenticated;
grant select on public.gn24_today_audit to authenticated;
revoke insert, update, delete on public.gn24_today_audit from anon, authenticated;
revoke delete on public.gn24_today_posts from anon, authenticated;

create or replace function public.gn24_is_regional_today_admin(p_region_code text)
returns boolean language sql stable security invoker set search_path=public as $$
 select exists(select 1 from public.gn24_reporters r
 where r.auth_user_id=auth.uid() and r.status='active'
 and r.organization_position='시·도본부장' and r.regional_hq_code=p_region_code);
$$;
revoke all on function public.gn24_is_regional_today_admin(text) from public;
grant execute on function public.gn24_is_regional_today_admin(text) to authenticated;

create policy "today public published read" on public.gn24_today_posts for select to anon
using (status='published' and hq_hidden=false);
create policy "today authenticated read" on public.gn24_today_posts for select to authenticated
using ((status='published' and hq_hidden=false) or author_user_id=(select auth.uid())
 or public.gn24_is_regional_today_admin(region_code) or public.is_gn24_admin());
create policy "today member insert" on public.gn24_today_posts for insert to authenticated
with check (author_user_id=(select auth.uid()) and status in ('draft','pending')
 and hq_hidden=false and featured=false and news_candidate=false and commercial_flag=false
 and approved_by is null and approved_at is null and published_at is null and hidden_at is null);
create policy "today member update own" on public.gn24_today_posts for update to authenticated
using (author_user_id=(select auth.uid()) and status in ('draft','pending','rejected') and hq_hidden=false)
with check (author_user_id=(select auth.uid()) and status in ('draft','pending')
 and hq_hidden=false and featured=false and news_candidate=false and commercial_flag=false
 and approved_by is null and approved_at is null and published_at is null and hidden_at is null);
create policy "today regional update" on public.gn24_today_posts for update to authenticated
using (public.gn24_is_regional_today_admin(region_code) and hq_hidden=false and status<>'hidden')
with check (public.gn24_is_regional_today_admin(region_code) and hq_hidden=false
 and status in ('pending','published','held','rejected') and featured=false and news_candidate=false);
create policy "today hq update" on public.gn24_today_posts for update to authenticated
using (public.is_gn24_admin()) with check (public.is_gn24_admin());
create policy "today audit hq read" on public.gn24_today_audit for select to authenticated
using (public.is_gn24_admin());
create policy "today audit regional read" on public.gn24_today_audit for select to authenticated
using (public.gn24_is_regional_today_admin(region_code));

create or replace function public.gn24_today_before_update()
returns trigger language plpgsql security invoker set search_path=public as $$
declare
 v_is_hq boolean := public.is_gn24_admin();
 v_is_owner boolean := old.author_user_id=auth.uid();
 v_is_regional boolean := public.gn24_is_regional_today_admin(old.region_code);
begin
 if v_is_regional and not v_is_hq and not v_is_owner then
  if new.author_user_id is distinct from old.author_user_id
   or new.author_display_name is distinct from old.author_display_name
   or new.region_code is distinct from old.region_code
   or new.category is distinct from old.category
   or new.title is distinct from old.title
   or new.body is distinct from old.body
   or new.image_url is distinct from old.image_url then
    raise exception 'REGIONAL_ADMIN_MODERATION_ONLY';
  end if;
 end if;
 new.updated_at:=now();
 if new.status='published' and old.status is distinct from 'published' then
  new.approved_by:=auth.uid(); new.approved_at:=coalesce(new.approved_at,now());
  new.published_at:=coalesce(new.published_at,now());
 end if;
 if new.status='hidden' then
  if not v_is_hq then raise exception 'HQ_ONLY_HIDDEN'; end if;
  new.hq_hidden:=true; new.hidden_at:=coalesce(new.hidden_at,now());
 elsif old.status='hidden' and new.status<>'hidden' then
  if not v_is_hq then raise exception 'HQ_ONLY_RESTORE'; end if;
  new.hq_hidden:=false; new.hidden_at:=null;
 end if;
 return new;
end; $$;
revoke all on function public.gn24_today_before_update() from public;

create or replace function public.gn24_today_audit_trigger()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.gn24_today_audit(post_id,actor_user_id,action,old_status,new_status,region_code)
 values(new.id,auth.uid(),
 case when tg_op='INSERT' then 'created'
      when old.status is distinct from new.status then 'status_changed' else 'updated' end,
 case when tg_op='UPDATE' then old.status else null end,new.status,new.region_code);
 return new;
end; $$;
revoke all on function public.gn24_today_audit_trigger() from public;

drop trigger if exists gn24_today_before_update_trg on public.gn24_today_posts;
create trigger gn24_today_before_update_trg before update on public.gn24_today_posts
for each row execute function public.gn24_today_before_update();
drop trigger if exists gn24_today_audit_trg on public.gn24_today_posts;
create trigger gn24_today_audit_trg after insert or update on public.gn24_today_posts
for each row execute function public.gn24_today_audit_trigger();

comment on table public.gn24_today_posts is 'GN24 TODAY reader life/community records; separate from NEWS and AD.';
comment on table public.gn24_today_audit is 'Immutable server-side audit trail for GN24 TODAY moderation actions.';
