-- GLOBAL NEWS24 v3.13.5
-- PHASE 7-6 reporter contribution ledger

create table if not exists public.gn24_contribution_rules (
  code text primary key,
  label text not null,
  default_amount integer not null default 0 check (default_amount >= 0),
  active boolean not null default true,
  notes text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.gn24_contribution_rules(code,label,default_amount,active,notes) values
('reporter','정식 기자',10000,true,'정식 기자 기본 운영분담금 기준'),
('regional_head','시·도본부장',50000,true,'시·도본부장 운영분담금 기준. 일반 기자분담금과 중복 부과하지 않음'),
('guest','객원기자',0,true,'기본 면제'),
('overseas','해외통신원',0,true,'초기 기본 면제 또는 본사 별도 결정')
on conflict (code) do update set label=excluded.label, default_amount=excluded.default_amount, active=excluded.active, notes=excluded.notes, updated_at=now();

create table if not exists public.gn24_contributions (
  id bigint generated by default as identity primary key,
  reporter_id text not null references public.gn24_reporters(id) on update cascade on delete restrict,
  contribution_month date not null,
  contribution_type text not null check (contribution_type in ('reporter','regional_head','guest','overseas','other')),
  amount integer not null default 0 check (amount >= 0),
  status text not null default 'unpaid' check (status in ('paid','unpaid','deferred','exempt')),
  payment_method text not null default 'bank_transfer' check (payment_method in ('bank_transfer','none','other')),
  paid_at timestamptz,
  memo text not null default '',
  confirmed_by uuid,
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reporter_id, contribution_month)
);

create index if not exists gn24_contributions_month_idx on public.gn24_contributions(contribution_month);
create index if not exists gn24_contributions_reporter_idx on public.gn24_contributions(reporter_id);
create index if not exists gn24_contributions_status_idx on public.gn24_contributions(status);

alter table public.gn24_contribution_rules enable row level security;
alter table public.gn24_contributions enable row level security;

revoke all on public.gn24_contribution_rules from anon;
revoke all on public.gn24_contributions from anon;
grant select, insert, update, delete on public.gn24_contribution_rules to authenticated;
grant select, insert, update, delete on public.gn24_contributions to authenticated;
grant usage, select on sequence public.gn24_contributions_id_seq to authenticated;

create policy "gn24 contribution rules admin all" on public.gn24_contribution_rules
for all to authenticated
using ((select public.is_gn24_admin()))
with check ((select public.is_gn24_admin()));

create policy "gn24 contributions admin all" on public.gn24_contributions
for all to authenticated
using ((select public.is_gn24_admin()))
with check ((select public.is_gn24_admin()));

create policy "gn24 contributions reporter read own" on public.gn24_contributions
for select to authenticated
using (reporter_id = (select public.gn24_my_reporter_id()));
