-- GLOBAL NEWS24 v3.13.10
-- PHASE 7-10 기자 교육·윤리·징계·포상 기록 시스템

create table if not exists public.gn24_reporter_records (
  id bigint generated by default as identity primary key,
  reporter_id text not null references public.gn24_reporters(id) on update cascade on delete restrict,
  record_type text not null check (record_type in ('training','award','warning','discipline','flagship')),
  record_date date not null default current_date,
  title text not null,
  description text not null default '',
  score integer not null default 0 check (score between -100 and 100),
  status text not null default 'active' check (status in ('active','revoked')),
  expires_at date null,
  evidence_url text not null default '',
  issued_by text not null default 'GLOBAL NEWS24 본사',
  created_by uuid null default auth.uid(),
  revoked_by uuid null,
  revoked_at timestamptz null,
  revoke_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gn24_reporter_records enable row level security;
create index if not exists gn24_reporter_records_reporter_date_idx on public.gn24_reporter_records(reporter_id,record_date desc);
create index if not exists gn24_reporter_records_type_status_idx on public.gn24_reporter_records(record_type,status);

revoke all on table public.gn24_reporter_records from anon;
grant select,insert,update on table public.gn24_reporter_records to authenticated;

drop policy if exists "hq read reporter records" on public.gn24_reporter_records;
create policy "hq read reporter records" on public.gn24_reporter_records for select to authenticated
using (public.is_gn24_admin() or public.gn24_my_access_level()='editor');

drop policy if exists "admin insert reporter records" on public.gn24_reporter_records;
create policy "admin insert reporter records" on public.gn24_reporter_records for insert to authenticated
with check (public.is_gn24_admin());

drop policy if exists "admin update reporter records" on public.gn24_reporter_records;
create policy "admin update reporter records" on public.gn24_reporter_records for update to authenticated
using (public.is_gn24_admin()) with check (public.is_gn24_admin());

create or replace function public.gn24_reporter_records_set_audit_fields()
returns trigger language plpgsql security invoker set search_path='public' as $$
begin
  new.updated_at := now();
  if old.status='active' and new.status='revoked' then
    new.revoked_at := coalesce(new.revoked_at,now());
    new.revoked_by := coalesce(new.revoked_by,auth.uid());
  end if;
  return new;
end;$$;

drop trigger if exists gn24_reporter_records_set_audit_fields on public.gn24_reporter_records;
create trigger gn24_reporter_records_set_audit_fields before update on public.gn24_reporter_records for each row execute function public.gn24_reporter_records_set_audit_fields();
revoke all on function public.gn24_reporter_records_set_audit_fields() from public,anon;
grant execute on function public.gn24_reporter_records_set_audit_fields() to authenticated;

-- v2 승급심사 집계: 기존 기사·취재·활동기간에 공식 인사기록을 결합한다.
drop function if exists public.gn24_admin_promotion_metrics_v2();
create function public.gn24_admin_promotion_metrics_v2()
returns table(
  reporter_id text,name text,reporter_number text,reporter_rank text,reporter_type text,organization_position text,regional_hq_code text,appointed_at timestamptz,active_days integer,published_articles bigint,submitted_reports bigint,avg_edit_score numeric,adverse_records bigint,training_count bigint,award_count bigint,flagship_count bigint,warning_count bigint,discipline_count bigint,personnel_score bigint,candidate_status text,target_rank text
)
language plpgsql security invoker set search_path='public' as $$
begin
  if not (public.is_gn24_admin() or public.gn24_my_access_level()='editor') then raise exception 'GN24 HQ access required'; end if;
  return query
  with article_counts as (
    select a.reporter_id,count(*)::bigint cnt from public.gn24_articles a where a.reporter_id is not null and a.is_published=true group by a.reporter_id
  ), submission_counts as (
    select s.reporter_id,count(*) filter(where s.submitted_at is not null or s.status<>'draft')::bigint cnt,round(avg(s.ai_edit_score)::numeric,1) avg_score from public.gn24_reporter_submissions s group by s.reporter_id
  ), personnel_audit as (
    select pa.reporter_id,count(*) filter(where pa.to_status in ('suspended','terminated') or pa.action in ('suspend','terminate','discipline','warning'))::bigint cnt from public.gn24_reporter_personnel_audit pa group by pa.reporter_id
  ), records as (
    select rr.reporter_id,
      count(*) filter(where rr.status='active' and rr.record_type='training')::bigint training_count,
      count(*) filter(where rr.status='active' and rr.record_type='award')::bigint award_count,
      count(*) filter(where rr.status='active' and rr.record_type='flagship')::bigint flagship_count,
      count(*) filter(where rr.status='active' and rr.record_type='warning')::bigint warning_count,
      count(*) filter(where rr.status='active' and rr.record_type='discipline')::bigint discipline_count,
      coalesce(sum(case when rr.status='active' then rr.score else 0 end),0)::bigint personnel_score
    from public.gn24_reporter_records rr group by rr.reporter_id
  )
  select r.id,r.name,r.reporter_number,r.reporter_rank,r.reporter_type,r.organization_position,r.regional_hq_code,
    coalesce(r.appointed_at,r.created_at),greatest(0,current_date-coalesce(r.appointed_at,r.created_at)::date)::integer,
    coalesce(ac.cnt,0)::bigint,coalesce(sc.cnt,0)::bigint,sc.avg_score,
    coalesce(pa.cnt,0)::bigint+coalesce(rec.warning_count,0)::bigint+coalesce(rec.discipline_count,0)::bigint,
    coalesce(rec.training_count,0)::bigint,coalesce(rec.award_count,0)::bigint,coalesce(rec.flagship_count,0)::bigint,coalesce(rec.warning_count,0)::bigint,coalesce(rec.discipline_count,0)::bigint,coalesce(rec.personnel_score,0)::bigint,
    case when r.status<>'active' then '활동상태 확인'
      when coalesce(rec.discipline_count,0)>0 then '징계기록 검토'
      when r.reporter_rank='기자' and (current_date-coalesce(r.appointed_at,r.created_at)::date)>=365 and coalesce(ac.cnt,0)>=50 and coalesce(sc.cnt,0)>=20 and coalesce(pa.cnt,0)=0 and coalesce(rec.warning_count,0)=0 and coalesce(rec.discipline_count,0)=0 then '선임기자 심사후보'
      when r.reporter_rank='선임기자' and (current_date-coalesce(r.appointed_at,r.created_at)::date)>=1095 and coalesce(ac.cnt,0)>=200 and coalesce(sc.cnt,0)>=80 and coalesce(pa.cnt,0)=0 and coalesce(rec.warning_count,0)=0 and coalesce(rec.discipline_count,0)=0 then '수석기자 심사후보'
      when r.reporter_rank='수석기자' then '최고 직급' else '기준 미충족' end,
    case when r.reporter_rank='기자' then '선임기자' when r.reporter_rank='선임기자' then '수석기자' else '' end
  from public.gn24_reporters r
  left join article_counts ac on ac.reporter_id=r.id
  left join submission_counts sc on sc.reporter_id=r.id
  left join personnel_audit pa on pa.reporter_id=r.id
  left join records rec on rec.reporter_id=r.id
  where r.reporter_type not in ('시민기자','청소년기자','어린이기자')
  order by case r.reporter_rank when '수석기자' then 1 when '선임기자' then 2 else 3 end,published_articles desc,r.name asc;
end;$$;
revoke all on function public.gn24_admin_promotion_metrics_v2() from public,anon;
grant execute on function public.gn24_admin_promotion_metrics_v2() to authenticated;
