import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
// PHASE 7-5 v3.11.4 security contract:
// JWT required. Caller must resolve to an approved GN24 reporter.
// Caller can confirm only a submission owned by their reporter_id and only from ai_draft.
// Confirmation changes status to editor_review. It never publishes an article.
// Runtime service credentials remain server-side only.
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}});
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405);const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"AUTH_REQUIRED"},401);const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const userSb=createClient(url,anon,{global:{headers:{Authorization:auth}}}),adminSb=createClient(url,service,{auth:{persistSession:false}});const body=await req.json().catch(()=>({}));const id=typeof body?.submission_id==='string'?body.submission_id.trim():'';if(!id)return json({error:"SUBMISSION_ID_REQUIRED"},400);const {data:rid}=await userSb.rpc("gn24_my_reporter_id");if(!rid)return json({error:"REPORTER_ACCESS_REQUIRED"},403);const {data:row}=await userSb.from("gn24_reporter_submissions").select("id,reporter_id,status,ai_title,ai_body").eq("id",id).maybeSingle();if(!row||row.reporter_id!==rid)return json({error:"NOT_FOUND"},404);if(row.status!=="ai_draft")return json({error:"STATUS_NOT_CONFIRMABLE"},409);if(!row.ai_title&&!row.ai_body)return json({error:"AI_DRAFT_REQUIRED"},409);const now=new Date().toISOString();const {error}=await adminSb.from("gn24_reporter_submissions").update({status:"editor_review",reviewed_at:now,updated_at:now}).eq("id",id).eq("reporter_id",rid).eq("status","ai_draft");if(error)return json({error:"CONFIRM_FAILED"},400);return json({ok:true,submission_id:id,status:"editor_review"});});